const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
const SIGNUP_SUCCESS =  'SIGNUP_SUCCESS';
const RESETPASSWORDLINK = 'RESETPASSWORDLINK';
const RESETPASSWORDLINKERROR = 'RESETPASSWORDLINKERROR';
const PASSWORDCONFIRM = 'PASSWORDCONFIRM';
const PASSWORDCONFIRMERROR = 'PASSWORDCONFIRMERROR';

const  ACTION_CONSTANTS = {
  SIGNUP_FAILURE,
  SIGNUP_SUCCESS,
  RESETPASSWORDLINK, 
  RESETPASSWORDLINKERROR,
  PASSWORDCONFIRM,
  PASSWORDCONFIRMERROR
};

export default ACTION_CONSTANTS;
