const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
const SIGNUP_SUCCESS =  'SIGNUP_SUCCESS';
const RESETPASSWORDLINK = 'RESETPASSWORDLINK';
const RESETPASSWORDLINKERROR = 'RESETPASSWORDLINKERROR';
const PASSWORDCONFIRM = 'PASSWORDCONFIRM';
const PASSWORDCONFIRMERROR = 'PASSWORDCONFIRMERROR';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

const  ACTION_CONSTANTS = {
  SIGNUP_FAILURE,
  SIGNUP_SUCCESS,
  RESETPASSWORDLINK, 
  RESETPASSWORDLINKERROR,
  PASSWORDCONFIRM,
  PASSWORDCONFIRMERROR,
  LOGIN_FAILURE,
  LOGIN_SUCCESS
};

export default ACTION_CONSTANTS;
